In [1]:
import numpy as np 
import pandas as pd
from tqdm import tqdm_notebook as tqdm

import Adanet

import pickle
import random
import time
import tensorflow as tf

W1105 08:03:39.336129 10520 deprecation_wrapper.py:119] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\adanet\tf_compat\__init__.py:87: The name tf.losses.Reduction is deprecated. Please use tf.compat.v1.losses.Reduction instead.

W1105 08:03:39.384813 10520 deprecation_wrapper.py:119] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\adanet\core\tpu_estimator.py:39: The name tf.estimator.tpu.TPUEstimator is deprecated. Please use tf.compat.v1.estimator.tpu.TPUEstimator instead.



In [2]:
path = 'D:\\庫存健診開發\\data\\Training\\processed\\DL\\'
cluster_num=0


In [3]:
classifier = Adanet.Train_adanet(df_path=path, cluster_num=cluster_num, ada_steps=3, epoch=10, batch_size=256, model_path='D:\\庫存健診開發\\model\\adanet\\', config_name='trial_2', penalty=0.001)

C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and

In [5]:
classifier.Net_train()

W1104 17:39:13.124195 11452 deprecation.py:323] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W1104 17:39:13.137188 11452 deprecation.py:323] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1104 17:39:13.139153 11452 deprecation.py:323] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\sit

W1104 17:42:19.703088 11452 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:42:19.727652 11452 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:42:20.330639 11452 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:42:20.355708 11452 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:42:25.685081 11452 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:42:25.710277 11452 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:42:26.280602 11452 metrics_impl.py:804] Trapezoidal rule is k

In [3]:
classifier = Adanet.Train_adanet(df_path=path, cluster_num=cluster_num, ada_steps=3, epoch=10, batch_size=256, model_path='C:\\Users\\011553\\Downloads\\', config_name='trial_6', penalty=0.001)

C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and

In [4]:
classifier.Evaluation('test')

W1105 08:04:04.594952 10520 deprecation.py:323] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1105 08:04:04.596301 10520 deprecation.py:323] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


ValueError: Required subnetwork builder is missing for iteration 0: CNN_2_32_1_32_0.001

In [7]:
classifier.Evaluation('validation')

W1104 17:14:48.518809  2548 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:14:48.544153  2548 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:14:49.110114  2548 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:14:49.130058  2548 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:14:49.846077  2548 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:14:49.871635  2548 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W1104 17:14:50.444193  2548 metrics_impl.py:804] Trapezoidal rule is k

[0.5780725883513047,
 0.5810742244128733,
 '              precision    recall  f1-score   support\n\n        down       0.60      0.43      0.50     13509\n          up       0.57      0.72      0.64     14083\n\n    accuracy                           0.58     27592\n   macro avg       0.59      0.58      0.57     27592\nweighted avg       0.59      0.58      0.57     27592\n']

In [5]:
tf.estimator.LinearClassifier(
                                                    feature_columns='x',
                                                                    config=self.make_config(self._config)),
                                                                cr.DNN_train_input_fn)

W1104 09:47:10.535294  4956 deprecation.py:323] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W1104 09:47:10.549256  4956 deprecation.py:323] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1104 09:47:10.553246  4956 deprecation.py:323] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\sit

AttributeError: 'str' object has no attribute 'name'

In [4]:
results = pd.DataFrame(columns = ['auc', 'acc', 'balance_acc', 'balance_auc'], index = ['train', 'val', 'test'])

In [11]:
results.loc['train', 'auc'] = 1
results

auc  acc balance_acc balance_auc
train    1  NaN         NaN         NaN
val    NaN  NaN         NaN         NaN
test   NaN  NaN         NaN         NaN

In [6]:
tf.feature_column.numeric_column(cr._X_train)

ValueError: key must be a string. Got: type <class 'numpy.ndarray'>. Given key: [[[0.006404   0.0064064  0.00633359 ... 0.22048663 0.5626594  0.17502338]
  [0.00638536 0.00638797 0.00631607 ... 0.22109355 0.54345465 0.16866493]
  [0.00636559 0.00636843 0.00629734 ... 0.21847849 0.55182564 0.17590156]
  ...
  [0.00594672 0.00595436 0.00588442 ... 0.23460542 0.47812933 0.20819461]
  [0.00592522 0.00593245 0.00586348 ... 0.23460542 0.47695705 0.2077586 ]
  [0.00590372 0.00591048 0.00584249 ... 0.23632681 0.4579806  0.24543263]]

 [[0.00638536 0.00638797 0.00631607 ... 0.22109355 0.54345465 0.16866493]
  [0.00636559 0.00636843 0.00629734 ... 0.21847849 0.55182564 0.17590156]
  [0.00634459 0.00634768 0.0062773  ... 0.22226804 0.5331998  0.16751853]
  ...
  [0.00592522 0.00593245 0.00586348 ... 0.23460542 0.47695705 0.2077586 ]
  [0.00590372 0.00591048 0.00584249 ... 0.23632681 0.4579806  0.24543263]
  [0.00588556 0.00589162 0.00582501 ... 0.23651737 0.69106907 0.39990222]]

 [[0.00636559 0.00636843 0.00629734 ... 0.21847849 0.55182564 0.17590156]
  [0.00634459 0.00634768 0.0062773  ... 0.22226804 0.5331998  0.16751853]
  [0.00632302 0.00632641 0.00625672 ... 0.22226804 0.5216073  0.17337565]
  ...
  [0.00590372 0.00591048 0.00584249 ... 0.23632681 0.4579806  0.24543263]
  [0.00588556 0.00589162 0.00582501 ... 0.23651737 0.69106907 0.39990222]
  [0.00587005 0.00587521 0.0058103  ... 0.24297675 0.6519737  0.2837524 ]]

 ...

 [[0.0123262  0.01221354 0.0123029  ... 0.23975922 0.60293466 0.34786263]
  [0.0123401  0.01222853 0.01231905 ... 0.8999453  0.6133282  0.37093318]
  [0.01235206 0.01224155 0.01233261 ... 0.57955456 0.654879   0.3001798 ]
  ...
  [0.01202063 0.01194052 0.01202396 ... 0.18768124 0.8716167  0.73155147]
  [0.01195911 0.011882   0.01196322 ... 0.17224336 0.8737722  0.7363997 ]
  [0.01189893 0.0118248  0.01190323 ... 0.17546564 0.8730761  0.7359766 ]]

 [[0.0123401  0.01222853 0.01231905 ... 0.8999453  0.6133282  0.37093318]
  [0.01235206 0.01224155 0.01233261 ... 0.57955456 0.654879   0.3001798 ]
  [0.01234753 0.01223851 0.01233078 ... 0.5780614  0.65517694 0.28705874]
  ...
  [0.01195911 0.011882   0.01196322 ... 0.17224336 0.8737722  0.7363997 ]
  [0.01189893 0.0118248  0.01190323 ... 0.17546564 0.8730761  0.7359766 ]
  [0.011841   0.01176981 0.01184484 ... 0.17546564 0.87281877 0.73563325]]

 [[0.01235206 0.01224155 0.01233261 ... 0.57955456 0.654879   0.3001798 ]
  [0.01234753 0.01223851 0.01233078 ... 0.5780614  0.65517694 0.28705874]
  [0.01232531 0.01221826 0.01231251 ... 0.4005169  0.65827966 0.2879188 ]
  ...
  [0.01189893 0.0118248  0.01190323 ... 0.17546564 0.8730761  0.7359766 ]
  [0.011841   0.01176981 0.01184484 ... 0.17546564 0.87281877 0.73563325]
  [0.01177387 0.01170583 0.01177735 ... 0.18523341 0.87876743 0.74792176]]].

In [10]:
results.loc['train', :] = a, c, a,c
results

auc       acc balance_acc balance_auc
train  0.626774  0.629256    0.626774    0.629256
val         NaN       NaN         NaN         NaN
test        NaN       NaN         NaN         NaN