In [1]:
import numpy as np # linear algebra
import pandas as pd
# from tqdm import tqdm
from tqdm import tqdm_notebook as tqdm
# tqdm.pandas()

from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.externals import joblib


import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation, Flatten, TimeDistributed, LeakyReLU, Conv1D, BatchNormalization, MaxPooling1D, AveragePooling1D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras import layers, optimizers
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l2

from xgboost import XGBClassifier, plot_importance

from Model_class import CNN_model, CNN_Tree_Classifier, CNN_Bagging, CNN_Boosting

import pickle
import random

C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
cluster = 0
with open(f'D:\\庫存健診開發\\data\\Training\\processed\\Cluster_{cluster}_classification_minmax0_Weekly', 'rb') as fp:
    load_list = pickle.load(fp)
len(load_list)

6

In [3]:
param = {'Conv_layer': 3,
                        'Dense_layer': 1,
                        'Dense': [128],
                        'dropout_ratio': [0.2, 0.2, 0.2],
                        'filter': [64, 128, 128],
                        'kernel': [3, 3, 3],
                        'padding': ['causal', 'causal', 'causal'],
                        'learning_rate': 0.001,
                        'batch': 256,
                        'epochs': 2}

p = {'n_estimator': 3, 'subsample': 0.8}

In [4]:
classifier = CNN_Boosting(load_list, Param = p, CNNparam=param)

In [5]:
classifier.get_dependent_variable()
classifier.CNN_train()

C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and

W1022 17:19:53.337582  2232 deprecation.py:506] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Train on 197067 samples, validate on 27592 samples
Epoch 1/2
197067/197067 - 5s - loss: 0.6766 - acc: 0.5794 - val_loss: 0.6733 - val_acc: 0.5794
Epoch 2/2
197067/197067 - 4s - loss: 0.6689 - acc: 0.5948 - val_loss: 0.6716 - val_acc: 0.5834


NameError: free variable 'prediction' referenced before assignment in enclosing scope

In [6]:
classifier.Evaluation()


[0.6360596275141183,
 0.6374979638377586,
 '              precision    recall  f1-score   support\n\n        down       0.65      0.57      0.61     15014\n          up       0.63      0.70      0.66     15681\n\n    accuracy                           0.64     30695\n   macro avg       0.64      0.64      0.64     30695\nweighted avg       0.64      0.64      0.64     30695\n']

In [9]:
classifier.Overall_Evaluation()

KeyboardInterrupt: 

In [3]:
classifier.save_model('D:\\庫存健診開發\\model\\test')

In [4]:
xgbc.fit(np.array(load_list[0]).reshape(len(load_list[0]), 20*20), np.array([item[2] for item in load_list[1]]))

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='gpu_hist', verbosity=1)

In [70]:
m = model.copy()
m.fit(classifier._X_train, classifier._y_train, validation_data=(classifier._X_val, classifier._y_val), batch_size=256, epochs=1, verbose=2)

AttributeError: 'Sequential' object has no attribute 'copy'

In [16]:
s = np.array([[1,0, 1,1,0], [0,1,0,0,1], [1,1,0,0,0]])
a = np.array([0.6, 0.4, 0.2])
[item * rate for item, rate in zip(s,a)]

[array([0.6, 0. , 0.6, 0.6, 0. ]),
 array([0. , 0.4, 0. , 0. , 0.4]),
 array([0.2, 0.2, 0. , 0. , 0. ])]

In [17]:
sum([item * rate for item, rate in zip(s,a)]) / sum(a)

array([0.66666667, 0.5       , 0.5       , 0.5       , 0.33333333])

In [15]:
[item * rate for item, rate in zip(s,a)]

[array([1, 2, 3, 4, 5]),
 array([ 2,  4,  6,  8, 10]),
 array([ 3,  6,  9, 12, 15])]

In [26]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])