In [2]:
import numpy as np # linear algebra
import pandas as pd
# from tqdm import tqdm
from tqdm import tqdm_notebook as tqdm
# tqdm.pandas()

from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.externals import joblib


import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation, Flatten, TimeDistributed, LeakyReLU, Conv1D, BatchNormalization, MaxPooling1D, AveragePooling1D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras import layers, optimizers
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l2

from xgboost import XGBClassifier, plot_importance

from Model_class import CNN_model, CNN_Tree_Classifier, CNN_Bagging, CNN_Boosting

import pickle
import random

In [3]:
cluster = 0
with open(f'D:\\庫存健診開發\\data\\Training\\processed\\Cluster_{cluster}_classification_minmax0_Weekly', 'rb') as fp:
    load_list = pickle.load(fp)
len(load_list)

6

In [5]:
param = {'Conv_layer': 3,
                        'Dense_layer': 1,
                        'Dense': [128],
                        'dropout_ratio': [0.2, 0.2, 0.2],
                        'filter': [64, 128, 128],
                        'kernel': [3, 3, 3],
                        'padding': ['causal', 'causal', 'causal'],
                        'learning_rate': 0.001,
                        'batch': 256,
                        'epochs': 10}



In [6]:
classifier = CNN_Tree_Classifier(load_list, classifier='xgboost', CNNparam=param)

W1021 17:20:24.060193 16324 deprecation.py:506] From C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [7]:
classifier.get_dependent_variable()
classifier.CNN_train()

C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and

Train on 197067 samples, validate on 27592 samples
Epoch 1/10
197067/197067 - 5s - loss: 0.6759 - auc: 0.6071 - val_loss: 0.6733 - val_auc: 0.6164
Epoch 2/10
197067/197067 - 4s - loss: 0.6682 - auc: 0.6281 - val_loss: 0.6751 - val_auc: 0.6107
Epoch 3/10
197067/197067 - 4s - loss: 0.6663 - auc: 0.6326 - val_loss: 0.6711 - val_auc: 0.6205
Epoch 4/10
197067/197067 - 4s - loss: 0.6652 - auc: 0.6349 - val_loss: 0.6708 - val_auc: 0.6212
Epoch 5/10
197067/197067 - 4s - loss: 0.6641 - auc: 0.6375 - val_loss: 0.6695 - val_auc: 0.6251
Epoch 6/10
197067/197067 - 4s - loss: 0.6633 - auc: 0.6392 - val_loss: 0.6696 - val_auc: 0.6246
Epoch 7/10
197067/197067 - 4s - loss: 0.6627 - auc: 0.6407 - val_loss: 0.6798 - val_auc: 0.6152
Epoch 8/10
197067/197067 - 4s - loss: 0.6623 - auc: 0.6416 - val_loss: 0.6713 - val_auc: 0.6242
Epoch 9/10
197067/197067 - 4s - loss: 0.6614 - auc: 0.6434 - val_loss: 0.6684 - val_auc: 0.6284
Epoch 10/10
197067/197067 - 4s - loss: 0.6614 - auc: 0.6435 - val_loss: 0.6708 - val_

In [6]:
print(classifier.Evaluation(target='validation')[2])

              precision    recall  f1-score   support

        down       0.59      0.57      0.58     13509
          up       0.60      0.61      0.61     14083

    accuracy                           0.59     27592
   macro avg       0.59      0.59      0.59     27592
weighted avg       0.59      0.59      0.59     27592



In [7]:
classifier.save_CNN('D:\\庫存健診開發\\code\\test')

In [8]:
print(r)

              precision    recall  f1-score   support

        down       0.62      0.64      0.63      4994
          up       0.70      0.68      0.69      6251

    accuracy                           0.66     11245
   macro avg       0.66      0.66      0.66     11245
weighted avg       0.66      0.66      0.66     11245



In [70]:
m = model.copy()
m.fit(classifier._X_train, classifier._y_train, validation_data=(classifier._X_val, classifier._y_val), batch_size=256, epochs=1, verbose=2)

AttributeError: 'Sequential' object has no attribute 'copy'

In [16]:
s = np.array([[1,0, 1,1,0], [0,1,0,0,1], [1,1,0,0,0]])
a = np.array([0.6, 0.4, 0.2])
[item * rate for item, rate in zip(s,a)]

[array([0.6, 0. , 0.6, 0.6, 0. ]),
 array([0. , 0.4, 0. , 0. , 0.4]),
 array([0.2, 0.2, 0. , 0. , 0. ])]

In [17]:
sum([item * rate for item, rate in zip(s,a)]) / sum(a)

array([0.66666667, 0.5       , 0.5       , 0.5       , 0.33333333])

In [15]:
[item * rate for item, rate in zip(s,a)]

[array([1, 2, 3, 4, 5]),
 array([ 2,  4,  6,  8, 10]),
 array([ 3,  6,  9, 12, 15])]

In [26]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])