In [1]:
import numpy as np 
import pandas as pd
from tqdm import tqdm_notebook as tqdm

from Model_class import CNN_model, CNN_Tree_Classifier, CNN_Bagging, CNN_Boosting
from Fine_Tune import Hyperparameter_Tuning as Tuning

import pickle
import random

C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
path = 'D:\\庫存健診開發\\data\\Training\\processed\\'

In [26]:
param = {'Conv_layer': [2],
        'Dense_layer': [1],
        'Dense': [64, 128, 256],
        'dropout_ratio': [0, 0.1, 0.15, 0.2, 0.25, 0.3],
        'filter': [64, 100, 128, 256],
        'kernel': [3, 5],
        'padding': ['causal'],
        'learning_rate': [0.001, 0.002, 0.003],
        'batch': [64, 128, 256, 512],
        'epochs': [1]}

rf_param = {'classifier': ['RandomForest'],
                'max_depth': [5, 10, 15, 20, 25, 30],
                'max_features': ['auto'],
                'min_samples_leaf': [0.05, 0.1, 0.15, 0.2],
                'min_samples_split': [0.05, 0.1, 0.15, 0.2],
                'n_estimators': [3]}

In [34]:
Optimization = Tuning(df_path=path, model='CNN_Tree_Classifier', CNNparam=param, Modelparam=rf_param, max_iter=1, cluster_num=0, model_keep=1)

In [30]:
Optimization.RandomSearch()

C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and

Train on 197067 samples, validate on 27592 samples
197067/197067 - 10s - loss: 0.6729 - auc_2: 0.6165 - val_loss: 0.6703 - val_auc_2: 0.6231
AUC:	0.5524240779158293 	 Accuracy:	0.5535662510872716 	 Accuracy Balance:	0.8493150684931506 	 AUC Balance:	0.9041095890410958


In [33]:
Optimization.save_optimal_model()
Optimization.save_optimal_param()

In [36]:
Optimization.Evaluation(1, target='validation')

[0.5524240779158293,
 0.5535662510872716,
 '              precision    recall  f1-score   support\n\n        down       0.55      0.50      0.52     13509\n          up       0.56      0.61      0.58     14083\n\n    accuracy                           0.55     27592\n   macro avg       0.55      0.55      0.55     27592\nweighted avg       0.55      0.55      0.55     27592\n']

In [35]:
Optimization.load_optimal_model()

C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\011553\AppData\Local\Continuum\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and

In [35]:
display(Optimization.results['CNN_params'].iloc[0])

{'Conv_layer': 2,
 'Dense_layer': 1,
 'Dense': [256],
 'dropout_ratio': [0.15, 0.25, 0],
 'filter': [100, 256],
 'kernel': [3, 3],
 'padding': ['causal', 'causal'],
 'learning_rate': 0.003,
 'batch': 256,
 'epochs': 1}

In [30]:
Optimization.load_optimal_param()

In [32]:
Optimization.results

auc       acc balance_acc balance_auc  \
0  0.552424  0.553566    0.849315     0.90411   

                                          CNN_params  \
0  {'Conv_layer': 2, 'Dense_layer': 1, 'Dense': [...   

                                        Model_params  
0  {'classifier': 'RandomForest', 'max_depth': 5,...

In [37]:
Optimization.results

auc       acc  balance_acc  balance_auc  \
0  0.552424  0.553566     0.849315      0.90411   

                                          CNN_params  \
0  {'Conv_layer': 2, 'Dense_layer': 1, 'Dense': [...   

                                        Model_params  
0  {'classifier': 'RandomForest', 'max_depth': 5,...

In [59]:
import os
os.listdir('D:\庫存健診開發\model\cluster0\CNN_Bagging\optimal_1')

['CNN_0.h5', 'CNN_1.h5']

In [29]:
Optimization.optimal[0].model_list[0].evaluate(Optimization.optimal[0]._X_val, Optimization.optimal[0]._y_val)

27592/27592 [==============================] - ETA: 1:12 - loss: 0.5995 - acc: 0.750 - ETA: 4s - loss: 0.6678 - acc: 0.6214  - ETA: 2s - loss: 0.6731 - acc: 0.601 - ETA: 2s - loss: 0.6691 - acc: 0.596 - ETA: 1s - loss: 0.6680 - acc: 0.598 - ETA: 1s - loss: 0.6691 - acc: 0.593 - ETA: 1s - loss: 0.6706 - acc: 0.588 - ETA: 1s - loss: 0.6713 - acc: 0.588 - ETA: 1s - loss: 0.6721 - acc: 0.585 - ETA: 1s - loss: 0.6721 - acc: 0.585 - ETA: 1s - loss: 0.6737 - acc: 0.580 - ETA: 0s - loss: 0.6744 - acc: 0.576 - ETA: 0s - loss: 0.6739 - acc: 0.578 - ETA: 0s - loss: 0.6743 - acc: 0.577 - ETA: 0s - loss: 0.6729 - acc: 0.580 - ETA: 0s - loss: 0.6735 - acc: 0.581 - ETA: 0s - loss: 0.6743 - acc: 0.579 - ETA: 0s - loss: 0.6749 - acc: 0.576 - ETA: 0s - loss: 0.6754 - acc: 0.575 - ETA: 0s - loss: 0.6755 - acc: 0.576 - ETA: 0s - loss: 0.6754 - acc: 0.577 - ETA: 0s - loss: 0.6754 - acc: 0.576 - ETA: 0s - loss: 0.6747 - acc: 0.579 - ETA: 0s - loss: 0.6738 - acc: 0.581 - ETA: 0s - loss: 0.6732 - acc: 0.583 -

[0.6730291616678169, 0.58462596]

In [33]:
a = 2
b = 3
l = [1,2]
l[0] = a
l

[2, 2]

In [36]:
np.log(2)

0.6931471805599453

In [35]:
Optimization.optimal[0]._vote_weight

[1.2098758045362112, 1.0484608118357972]

In [40]:
sum(np.array(Optimization.optimal[0].prediction_list))

array([0, 0, 0, ..., 2, 2, 2])

In [41]:
sum(np.array([item * rate for item, rate in zip(Optimization.optimal[0].prediction_list,Optimization.optimal[0]._vote_weight)]))/sum(np.array(Optimization.optimal[0]._vote_weight))

TypeError: can't multiply sequence by non-int of type 'numpy.float64'

In [46]:
np.array(Optimization.optimal[0].prediction_list)[0] * np.array(Optimization.optimal[0]._vote_weight)[0]

array([0.       , 0.       , 0.       , ..., 1.2098758, 1.2098758,
       1.2098758])

In [47]:
np.array(Optimization.optimal[0].prediction_list)[1] * np.array(Optimization.optimal[0]._vote_weight)[1]

array([0.        , 0.        , 0.        , ..., 1.04846081, 1.04846081,
       1.04846081])

In [49]:
vpte = sum(np.array([item * rate for item, rate in zip(np.array(Optimization.optimal[0].prediction_list), np.array(Optimization.optimal[0]._vote_weight))]))/sum(np.array(Optimization.optimal[0]._vote_weight))

In [55]:
p = np.array([1 if v > 0.5 else 0 for v in vpte])

In [54]:
print(vpte[:20])

[0.         0.         0.         0.         0.         0.
 0.53573758 0.53573758 1.         1.         1.         1.
 0.46426242 0.46426242 0.46426242 0.46426242 0.46426242 0.46426242
 0.46426242 0.46426242]


In [56]:
print(p[:20])

[0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
